In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from google.colab import files
df=files.upload()

Saving archive (7).zip to archive (7).zip

In [4]:
df.keys()

dict_keys(['archive (7).zip'])

In [11]:
import zipfile

with zipfile.ZipFile('archive (7).zip', 'r') as zip_ref:
    zip_ref.extractall('/content/')

In [12]:
import os
os.listdir()

['.config',
 'olist_sellers_dataset.csv',
 'olist_order_items_dataset.csv',
 'olist_geolocation_dataset.csv',
 'olist_customers_dataset.csv',
 'olist_products_dataset.csv',
 'olist_order_reviews_dataset.csv',
 'archive (7).zip',
 'product_category_name_translation.csv',
 'olist_order_payments_dataset.csv',
 'olist_orders_dataset.csv',
 'sample_data']

In [14]:
customers=pd.read_csv('olist_customers_dataset.csv')
geolocation=pd.read_csv('olist_geolocation_dataset.csv')
orders=pd.read_csv('olist_orders_dataset.csv')
order_items=pd.read_csv('olist_order_items_dataset.csv')
orders_reviews=pd.read_csv('olist_order_reviews_dataset.csv')
orders_payments=pd.read_csv('olist_order_payments_dataset.csv')
products=pd.read_csv('olist_products_dataset.csv')
sellers=pd.read_csv('olist_sellers_dataset.csv')
product_category=pd.read_csv('product_category_name_translation.csv')

In [15]:
customers.shape
orders.shape
order_items.shape

(112650, 7)

In [17]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='object')

In [18]:
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_delivered_customer_date'] = pd.to_datetime(orders['order_delivered_customer_date'])
orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])

In [19]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

In [21]:
orders["delivery_time"]=orders["order_delivered_customer_date"]-orders["order_purchase_timestamp"]
orders["delay"]=orders["order_delivered_customer_date"]-orders["order_estimated_delivery_date"]
orders["delayed"]=orders["delay"].apply(lambda x: 1 if x.total_seconds() > 0 else 0)

In [24]:
orders[orders["delayed"]==1]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_time,delay,delayed
20,203096f03d82e0dffbc41ebc2e2bcfb7,d2b091571da224a1b36412c18bc3bbfe,delivered,2017-09-18 14:31:30,2017-09-19 04:04:09,2017-10-06 17:50:03,2017-10-09 22:23:46,2017-09-28,21 days 07:52:16,11 days 22:23:46,1
25,fbf9ac61453ac646ce8ad9783d7d0af6,3a874b4d4c4b6543206ff5d89287f0c3,delivered,2018-02-20 23:46:53,2018-02-22 02:30:46,2018-02-26 22:25:22,2018-03-21 22:03:54,2018-03-12,28 days 22:17:01,9 days 22:03:54,1
35,8563039e855156e48fccee4d611a3196,5f16605299d698660e0606f7eae2d2f9,delivered,2018-02-17 15:59:46,2018-02-17 16:15:34,2018-02-20 23:03:56,2018-03-20 00:59:25,2018-03-20,30 days 08:59:39,0 days 00:59:25,1
41,6ea2f835b4556291ffdc53fa0b3b95e8,c7340080e394356141681bd4c9b8fe31,delivered,2017-11-24 21:27:48,2017-11-25 00:21:09,2017-12-13 21:14:05,2017-12-28 18:59:23,2017-12-21,33 days 21:31:35,7 days 18:59:23,1
57,66e4624ae69e7dc89bd50222b59f581f,684fa6da5134b9e4dab731e00011712d,delivered,2018-03-09 14:50:15,2018-03-09 15:40:39,2018-03-15 00:31:19,2018-04-03 13:28:46,2018-04-02,24 days 22:38:31,1 days 13:28:46,1
...,...,...,...,...,...,...,...,...,...,...,...
99396,b3112ca67f3afd4e20cf2ee91fc4f804,6f83c71b6c044fb156d697d4130fe9b5,delivered,2018-08-02 22:46:54,2018-08-02 23:04:06,2018-08-15 17:42:00,2018-08-21 00:03:26,2018-08-16,18 days 01:16:32,5 days 00:03:26,1
99397,0fa1fab1d7c1211c824596ed5e111e3c,7f3bd6c94d2daf7b6462d1a894a775b4,delivered,2018-03-13 21:48:57,2018-03-13 22:40:28,2018-03-14 19:27:23,2018-04-05 19:59:49,2018-04-02,22 days 22:10:52,3 days 19:59:49,1
99423,38e9133ce29f6bbe35aed9c3863dce01,ad312389a098ceff46ce92c4595c06d0,delivered,2017-10-12 20:54:11,2017-10-14 03:28:24,2017-10-17 17:04:42,2017-11-21 17:06:59,2017-10-31,39 days 20:12:48,21 days 17:06:59,1
99425,d692ef54145c9cb3322ec2e5508aa3f4,82ddfcf9438b0cd1117b55ac33184df8,delivered,2018-03-21 19:47:18,2018-03-21 20:05:26,2018-03-22 21:11:58,2018-04-11 00:48:31,2018-04-09,20 days 05:01:13,2 days 00:48:31,1
99432,cfa78b997e329a5295b4ee6972c02979,a2f7428f0cafbc8e59f20e1444b67315,delivered,2017-12-20 09:52:41,2017-12-20 10:09:52,2017-12-20 20:25:25,2018-01-26 15:45:14,2018-01-18,37 days 05:52:33,8 days 15:45:14,1

In [25]:
order_value=order_items.groupby("order_id")["price"].sum().reset_index()
order_value.rename(columns={"price":"total_order_value"},inplace=True)

In [26]:
order_value

                               order_id  total_order_value
0      00010242fe8c5a6d1ba2dd792cb16214              58.90
1      00018f77f2f0320c557190d7a144bdd3             239.90
2      000229ec398224ef6ca0657da4fc703e             199.00
3      00024acbcdf0a6daa1e931b038114c75              12.99
4      00042b26cf59d7ce69dfabb4e55b4fd9             199.90
...                                 ...                ...
98661  fffc94f6ce00a00581880bf54a75a037             299.99
98662  fffcd46ef2263f404302a634eb57f7eb             350.00
98663  fffce4705a9662cd70adb13d4a31832d              99.90
98664  fffe18544ffabc95dfada21779c9644f              55.99
98665  fffe41c64501cc87c801fd61db3f6244              43.00

[98666 rows x 2 columns]

In [28]:
df = orders.merge(customers, on='customer_id', how='left')

df = df.merge(order_items, on='order_id', how='left')

df = df.merge(order_value, on='order_id', how='left')

df = df.merge(orders_payments, on='order_id', how='left')

df = df.merge(orders_reviews, on='order_id', how='left')

df = df.merge(products, on='product_id', how='left')

In [29]:
df["order_month"]=df["order_purchase_timestamp"].dt.to_period("M")
df["order_day"]=df["order_purchase_timestamp"].dt.day_name()
df["is_weekend"]=df["order_day"].isin(["Saturday","Sunday"]).astype(int)

In [30]:
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_time,delay,...,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,order_month,order_day,is_weekend
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8 days 10:28:40,-8 days +21:25:13,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,2017-10,Monday,0
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8 days 10:28:40,-8 days +21:25:13,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,2017-10,Monday,0
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,8 days 10:28:40,-8 days +21:25:13,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,2017-10,Monday,0
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,13 days 18:46:08,-6 days +15:27:45,...,29.0,178.0,1.0,400.0,19.0,13.0,19.0,2018-07,Tuesday,0
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,9 days 09:27:40,-18 days +18:06:29,...,46.0,232.0,1.0,420.0,24.0,19.0,21.0,2018-08,Wednesday,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119138,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,22 days 04:38:58,-2 days +17:37:56,...,52.0,828.0,4.0,4950.0,40.0,10.0,40.0,2018-02,Tuesday,0
119139,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,24 days 20:37:34,-6 days +11:24:17,...,51.0,500.0,2.0,13300.0,32.0,90.0,22.0,2017-08,Sunday,1
119140,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,17 days 02:04:27,-21 days +23:32:54,...,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0,2018-01,Monday,0
119141,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,17 days 02:04:27,-21 days +23:32:54,...,59.0,1893.0,1.0,6550.0,20.0,20.0,20.0,2018-01,Monday,0
119142,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,7 days 16:11:00,-18 days +13:08:30,...,45.0,569.0,1.0,150.0,16.0,7.0,15.0,2018-03,Thursday,0

In [32]:
df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'delivery_time', 'delay', 'delayed', 'customer_unique_id',
       'customer_zip_code_prefix', 'customer_city', 'customer_state',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value', 'total_order_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value', 'review_id',
       'review_score', 'review_comment_title', 'review_comment_message',
       'review_creation_date', 'review_answer_timestamp',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'order_month', 'order_day', 'is_weekend'],
      dtype='object')

In [35]:
delayed_orders = df[df["delayed"] == 1][["order_id","total_order_value"]]

In [48]:
len(df[df["delayed"]==1])

9068

In [43]:
df.shape

(119143, 43)

In [45]:
columns_to_drop = [
    'customer_unique_id','order_item_id','product_id','seller_id','review_id',
    'review_comment_title','review_comment_message',
    'product_description_lenght',
    'product_weight_g','product_length_cm','product_height_cm','product_width_cm',
    'price','freight_value','payment_sequential','payment_installments',
    'order_approved_at','order_delivered_carrier_date','shipping_limit_date',
    'review_creation_date','review_answer_timestamp'
]

df = df.drop(columns=columns_to_drop)

In [46]:
df.shape

(119143, 22)

In [49]:
df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_delivered_customer_date    3421
order_estimated_delivery_date       0
delivery_time                    3421
delay                            3421
delayed                             0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
total_order_value                 833
payment_type                        3
payment_value                       3
review_score                      997
product_category_name            2542
product_name_lenght              2542
product_photos_qty               2542
order_month                         0
order_day                           0
is_weekend                          0
dtype: int64

In [50]:
df=df[df["order_delivered_customer_date"].notna()]

In [53]:
df = df[df["total_order_value"].notna()]

In [54]:
df["review_score"].fillna(0,inplace=True)

/tmp/ipykernel_6191/333981979.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["review_score"].fillna(0,inplace=True)

In [57]:
df["product_category_name"].fillna('Unknown', inplace=True)

/tmp/ipykernel_6191/1425065534.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["product_category_name"].fillna('Unknown', inplace=True)

In [ ]:
df = df.drop(columns=["product_name_lenght","product_photos_qty"])

In [60]:
df.isnull().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_delivered_customer_date    0
order_estimated_delivery_date    0
delivery_time                    0
delay                            0
delayed                          0
customer_zip_code_prefix         0
customer_city                    0
customer_state                   0
total_order_value                0
payment_type                     3
payment_value                    3
review_score                     0
product_category_name            0
order_month                      0
order_day                        0
is_weekend                       0
dtype: int64

In [59]:
df.shape

(115722, 20)

In [62]:
from google.colab import files
df.to_csv("Olist Brazilian E-commerce Dataset.csv", index=False)
files.download("Olist Brazilian E-commerce Dataset.csv")